config/routes.rb
Rails.application.routes.draw do
  get 'suggestions/index'
  get 'suggestions/show'

  devise_for :users
  authenticated :user do
    root to: 'pages#home_user', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'pages#home', as: :unauthenticated_root

  end

  # The vinyls that the user own in his collection:
  resources :user_vinyls, only: [:index, :show, :update, :destroy] do
    member do
      patch :update_tag
    end
  end
  # TODO: :
  # -- SHOULD HAVE --
  # :users
  # :listen
  # :index from other users

  # The vinyls that the user has put in his wish list:
  resources :favorites, only: [:index, :show, :destroy] do
    member do
      post :create_from_favorite
    end
    resources :user_vinyls, only: [:create_from_favorite]
  end

  # The vinyls that the user doesn't own:
  resources :vinyls, only: [:index, :show] do
    collection do
      get :barcode
      get :scan
      get :search
    end
    resources :favorites, only: [:create]
    resources :user_vinyls, only: [:create]
  end

  # The vinyls that are suggested for the user :
  resources :suggestions, only: [:index, :show]
  resources :vinyl_tags, only: [:destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :vinyl
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @user = current_user
    if params[:query].present?
      sql_query = "title ILIKE :query OR name ILIKE :query"
      @favorites = @user.favorites.joins(vinyl: :artist).where(sql_query, query: "%#{params[:query]}%")
    else
      @favorites = @user.favorites.all
    end
  end

  def create_from_favorite
    @favorite = Favorite.find(params[:id])
    @user = current_user
    @user_vinyl = UserVinyl.create(user: @user, vinyl_id: @favorite[:vinyl_id])
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to user_vinyl_path(@user_vinyl)
  end

  def create
    @user = current_user
    @vinyl = Vinyl.find(params[:vinyl_id])
    @favorite = Favorite.create(user: @user, vinyl: @vinyl)
    redirect_to vinyl_path(@vinyl)
  end

  def show
    @favorite = Favorite.find(params[:id])
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    head :no_content
  end
end

app/views/favorites/index.html.erb
<%= render 'shared/loader_search' %>
<div class="m-5"></div>

<div class="d-flex justify-content-between align-items-center m-3">
  <div class="avatar-navbar">
    <%= render 'shared/avatar_navbar' %>
  </div>
  <h2 class="font-weight-bold header-search-h2"><span class="vinyl-count"><%= @favorites.count %></span> vinyls in your wishlist</h2>
</div>

<ul class="nav justify-content-between p-3">
  <li class="nav-item font-weight-bold text-hidden"><%= link_to 'Collection', user_vinyls_path, style:"color:#c2c2c2;" %></li>
  <li class="nav-item font-weight-bold text-hidden"><%= link_to 'Suggestions', suggestions_path, id:"btn-search", style:"color:#c2c2c2;" %></li>
  <li class="nav-item font-weight-bold">Wishlist</li>
</ul>

<div class="card-vinyl">
  <div class="ml-3 mr-3 mb-3 content-search" style="padding-bottom : 45px;">
    <% @favorites.reverse_each do |favorite| %>

      <div class="d-flex card-search py-4 g-0">
        <%= link_to favorite_path(favorite), style: "width:280px" do %>
          <div class="container-img">
            <img class="photo-sizing" src="<%= favorite.vinyl.cover_url %>">
          </div>
          <div class="container-infos w-100 px-3 py-2 d-flex flex-column justify-content-between">
            <div>
              <h6 class="card-text title-sizing text-white"><%= favorite.vinyl.title %></h6>
              <p class="card-text text-sizing text-white"><%= favorite.vinyl.artist.name %></p>
            </div>
            <p class="card-text genre-color"><small><i class="fas fa-music"></i> <%= favorite.vinyl.genre.name %></small></p>
          </div>
        <% end %>
          <div class="h-75 pr-3 pl-3 pb-3 pt-2 link-card justify-content-between align-items-center d-flex flex-column">
            <%= link_to icon('fas', 'plus'), create_from_favorite_favorite_path(favorite), method: :post %>
            <%= link_to icon('fas', 'trash-alt'), favorite_path(favorite), method: :delete, remote: true, class:"my-trash text-white", id:'trash' %>
          </div>
      </div>

    <% end %>
  </div>
</div>

app/views/favorites/show.html.erb
<div class="banner-vinyl" style="background-image: linear-gradient(180deg, rgba(0,0,0,0.8239670868347339) 0%, rgba(253,187,45,0) 20%), url('<%= @favorite.vinyl.cover_url %>');">
  <div class="d-flex flex-row-reverse p-3">
      <%= image_tag 'fav-diamond.svg', style:'height:20px;'%>
  </div>
</div>
<div class="infos bg-light mb-4">
  <div class="d-flex justify-content-between align-items-center">
    <h2 class="text-primary title-sizing"><%= @favorite.vinyl.title %></h2>
    <small id="rate"><%= image_tag 'rating.svg', class:"mr-1" %><%= @favorite.vinyl.stars %></small>
  </div>
  <div class="artist-year">
    <small class="text-muted">by <%= @favorite.vinyl.artist.name %> - <%= @favorite.vinyl.release_date %></small>
  </div>
  <div class="tracks-index mt-3">
      <ul class="pl-0 bg-light">
        <% @favorite.vinyl.tracks.each do |track| %>
          <li><%= track.position %>. <%= track.title %></li>
        <% end %>
      </ul>
  </div>
</div>