config/routes.rb
Rails.application.routes.draw do
  get 'suggestions/index'
  get 'suggestions/show'

  devise_for :users
  authenticated :user do
    root to: 'pages#home_user', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'pages#home', as: :unauthenticated_root

  end

  # The vinyls that the user own in his collection:
  resources :user_vinyls, only: [:index, :show, :update, :destroy] do
    member do
      patch :update_tag
    end
  end
  # TODO: :
  # -- SHOULD HAVE --
  # :users
  # :listen
  # :index from other users

  # The vinyls that the user has put in his wish list:
  resources :favorites, only: [:index, :show, :destroy] do
    member do
      post :create_from_favorite
    end
    resources :user_vinyls, only: [:create_from_favorite]
  end

  # The vinyls that the user doesn't own:
  resources :vinyls, only: [:index, :show] do
    collection do
      get :barcode
      get :scan
      get :search
    end
    resources :favorites, only: [:create]
    resources :user_vinyls, only: [:create]
  end

  # The vinyls that are suggested for the user :
  resources :suggestions, only: [:index, :show]
  resources :vinyl_tags, only: [:destroy]
end

app/views/shared/_add-favorite-link.html.erb
<div id="lozenge-gold" class="d-flex flex-row-reverse py-3 px-2">
  <%= link_to icon('fas', 'gem'), vinyl_favorites_path(@vinyl), method: :post, class:"diamond-fav add-favorite-link p-3", style: "font-size: 1.4rem;text-decoration: none;" %>
</div>

app/views/shared/_avatar_navbar.html.erb
<li class="nav-item dropdown">
  <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
  <div class="dropdown-menu dropdown-menu-right text-right" aria-labelledby="navbarDropdown">
    <%= link_to "My Collection", user_vinyls_path, class: "dropdown-item" %>
    <%= link_to "My Suggestion", suggestions_path, class: "dropdown-item" %>
    <%= link_to "My Wish-list", favorites_path, class: "dropdown-item" %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
  </div>
</li>

app/views/shared/_back-arrow-devise.html.erb
<div class="d-flex w-100 fixed-bottom p-3">
  <% img = image_tag 'back-arrow.svg' %>
  <%= link_to img, unauthenticated_root_path %>
</div>

app/views/shared/_back-arrow.html.erb
<div class="d-flex w-100 fixed-bottom p-3">
  <% img = image_tag 'back-arrow.svg' %>
  <%= link_to img, _back_url %>
</div>

app/views/shared/_bookmark-green.html.erb
<i class="fas fa-bookmark bookmark-green"></i>

app/views/shared/_card-vinyl.html.erb
<div class="banner-vinyl" style="background-image: url(<%= @user_vinyl.vinyl.cover_url %>)">
  <div class="d-flex flex-row-reverse p-3">
    <%= render 'shared/checkbox' %>
  </div>
</div>
<div class="infos bg-light mb-4">
  <div class="d-flex justify-content-between align-items-center">
    <h2 class="text-primary"><%= @user_vinyl.vinyl.title %></h2>
    <small id="rate"><%= image_tag 'rating', class:"mr-1" %><%= @user_vinyl.vinyl.stars %></small>
  </div>
  <div class="artist-year">
    <small class="text-muted">by <%= @user_vinyl.vinyl.artist.name %>-<%= @user_vinyl.vinyl.release_date %></small>
  </div>
</div>
<%= render 'shared/btn-collection' %>
<%= render 'shared/back-arrow' %>

app/views/shared/_collection-bottom-navbar.html.erb
<div class="collection-navbar d-flex w-100 justify-content-end fixed-bottom p-3">
  <% collection = image_tag 'collection-gold.png' %>
  <%= link_to collection, user_vinyls_path %>
</div>

app/views/shared/_dark-bottom-navbar.html.erb
<div class="dark-show-navbar d-flex w-100 justify-content-between fixed-bottom p-3">
  <% search = image_tag 'search-dark.svg' %>
  <% collection = image_tag 'collection-dark.svg' %>
  <% back_arrow = image_tag 'chevron-gold.png' %>


  <%= link_to back_arrow, _back_url %>  <%# authenticated_root_path %>
  <div class="circle-btn-scan">
    <%= link_to search, authenticated_root_path  %>
  </div>
  <%= link_to collection, user_vinyls_path %>
</div>

app/views/shared/_delete-favorite-link.html.erb
<div id="lozenge-green" class="d-flex flex-row-reverse py-3 px-2">
  <%= link_to icon('fas', 'gem'), favorite_path(@favorite), method: :delete, class:"diamond-fav delete-favorite-link p-3", style: "font-size: 1.4rem;text-decoration: none;" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_loader_search.html.erb
<div class="content-loader">
  <%= image_tag 'compact-disc.svg', style: "width: 50px;" %>
  <h2 class="search-title">Wait, Diamond is searching ...</h2>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div class="my-form col-12">
  <%= form_tag user_vinyls_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      required: true,
      class: "my-form-input form-control col-8",
      placeholder: "Search artist, album" %>
    <%= submit_tag "Search", class: "my-form-button btn btn-info col-4" %>
  <% end %>
</div>

app/views/shared/_white-bottom-navbar.html.erb
<div class="white-navbar d-flex w-100 justify-content-between fixed-bottom p-3">
  <% search = image_tag 'search-dark.svg' %>
  <% collection = image_tag 'collection-white.svg' %>
  <% back_arrow = image_tag 'chevron-gold.png' %>

  <%= link_to back_arrow, _back_url %> <%# authenticated_root_path %>
  <div class="circle-btn-scan">
    <%= link_to search, authenticated_root_path  %>
  </div>
  <%= link_to collection, user_vinyls_path %>
</div>