config/routes.rb
Rails.application.routes.draw do
  get 'suggestions/index'
  get 'suggestions/show'

  devise_for :users
  authenticated :user do
    root to: 'pages#home_user', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'pages#home', as: :unauthenticated_root

  end

  # The vinyls that the user own in his collection:
  resources :user_vinyls, only: [:index, :show, :update, :destroy] do
    member do
      patch :update_tag
    end
  end
  # TODO: :
  # -- SHOULD HAVE --
  # :users
  # :listen
  # :index from other users

  # The vinyls that the user has put in his wish list:
  resources :favorites, only: [:index, :show, :destroy] do
    member do
      post :create_from_favorite
    end
    resources :user_vinyls, only: [:create_from_favorite]
  end

  # The vinyls that the user doesn't own:
  resources :vinyls, only: [:index, :show] do
    collection do
      get :barcode
      get :scan
      get :search
    end
    resources :favorites, only: [:create]
    resources :user_vinyls, only: [:create]
  end

  # The vinyls that are suggested for the user :
  resources :suggestions, only: [:index, :show]
  resources :vinyl_tags, only: [:destroy]
end

app/models/user_vinyl.rb
class UserVinyl < ApplicationRecord
  belongs_to :vinyl
  belongs_to :user

  has_many :vinyl_tags
  has_many :tags, through: :vinyl_tags, dependent: :destroy
end

app/controllers/user_vinyls_controller.rb
class UserVinylsController < ApplicationController
  def index
    @user = current_user
    if params[:query].present?
      sql_query = "title ILIKE :query OR name ILIKE :query"
      @user_vinyls = UserVinyl.joins(vinyl: :artist).where(sql_query, query: "%#{params[:query]}%")
    else
      @user_vinyls = @user.user_vinyls.all
    end

    arr = []
    @user_vinyls.each do |vinyl|
      arr << vinyl.vinyl.genre_id
    end
    @hash_vinyl = arr.group_by { |i| i }
    @hash_top_vinyl = @hash_vinyl.sort_by {|_key, value| value.length}
    @hash_top_vinyl.reverse!
    @first_genre = @hash_top_vinyl[0]
    @second_genre = @hash_top_vinyl[1]
    @third_genre = @hash_top_vinyl[2]
  end

  def create
    @vinyl = Vinyl.find(params[:vinyl_id])
    @user = current_user
    @user_vinyl = UserVinyl.create(vinyl: @vinyl, user: @user)
    redirect_to user_vinyl_path(@user_vinyl)
  end

  def update_tag
    @user_vinyl = UserVinyl.find(params[:id])
    @tag = Tag.find(params[:format])
    @vinyl_tag = VinylTag.create(tag: @tag, user_vinyl: @user_vinyl)
    redirect_to user_vinyl_path(params[:id])
  end

  def show

    @user_vinyl = UserVinyl.find(params[:id])
    @tags = Tag.all
    @vinyl_tags = @user_vinyl.vinyl_tags.all
  end

  def update
    @user_vinyl = UserVinyl.find(params[:id])
    @tag = Tag.find(params[:user_vinyl][:vinyl_tags])
    @vinyl_tag = VinylTag.create(tag: @tag, user_vinyl: @user_vinyl)
    redirect_to user_vinyl_path(params[:id])
  end

  def destroy
    @user_vinyl = UserVinyl.find(params[:id])
    @user_vinyl.destroy
    head :no_content
  end

  private

  def user_vinyl_params
    params.require(:user_vinyl).permit(:user_id, :vinyl_id)
  end
end

app/views/user_vinyls/index.html.erb
<%= render 'shared/loader_search' %>
<div class="m-5">
</div>

<div class="d-flex justify-content-between align-items-center m-3">
  <div class="avatar-navbar">
    <%= render 'shared/avatar_navbar' %>
  </div>
  <h2 class="font-weight-bold header-search-h2"><span class="vinyl-count"><%= @user_vinyls.count %></span> vinyls in your collection</h2>
</div>

<ul class="nav justify-content-between p-3">
  <li class="nav-item font-weight-bold">Collection</li>
  <li class="nav-item text-hidden"><%= link_to 'Suggestions', suggestions_path, id:"btn-search", style:"color:#c2c2c2;" %></li>
  <li class="nav-item text-hidden"><%= link_to 'Wishlist', favorites_path, style:"color:#c2c2c2;" %></li>
</ul>

<div class="music-kind-view">
    <% if @third_genre %>
      <% genre_first = Genre.find(@hash_top_vinyl[0][0]) %>
      <% genre_second = Genre.find(@hash_top_vinyl[1][0]) %>
      <% genre_third = Genre.find(@hash_top_vinyl[2][0]) %>
      <div class="d-flex align-items-end">
        <div class="count text-center p-1" style="min-width: 50px; height: 50px;"><p><%= genre_second.name %></p><div class="counter font-weight-bold"><%= @hash_top_vinyl[1][1].count  %></div></div>
        <div class="count text-center p-1" style="min-width: 50px; height: 75px;"><p><%= genre_first.name %></p><div class="counter font-weight-bold"><%= @hash_top_vinyl[0][1].count  %></div></div>
        <div class="count text-center p-1" style="min-width: 50px; height: 25px;"><p><%= genre_third.name %></p><div class="counter font-weight-bold"><%= @hash_top_vinyl[2][1].count  %></div></div>
      </div>
    <% end %>
</div>

<div class="card-vinyl overflow-hidden">
  <div class="search-bar">
    <%= form_tag user_vinyls_path, method: "GET", class:"home-form-search w-100 d-flex justify-content-center" do %>
      <%= text_field_tag :query,
          params[:query],
          required: false,
          class: "form-control home-input",
          placeholder: "Nevermind..."
      %>
    <%= button_tag(type: "submit",id: "btn-search", class: "btn-mid-gold btn-search-home") do %>
      <i class="fas fa-search"></i>
    <% end %>
    <% end %>
  </div>
  <div class="m-3 content-search" style="padding-bottom : 45px;">
    <% @user_vinyls.reverse_each do |user_vinyl| %>
      <div class="d-flex card-search py-4 g-0">
        <%= link_to user_vinyl_path(user_vinyl) do %>
          <div class="container-img">
            <img class="photo-sizing" src="<%= user_vinyl.vinyl.cover_url %>">
          </div>
          <div class="container-infos w-100 px-3 py-2 d-flex flex-column justify-content-between">
            <div>
              <h6 class="card-text title-sizing text-white"><%= user_vinyl.vinyl.title %></h6>
              <p class="card-text text-sizing text-white"><%= user_vinyl.vinyl.artist.name %></p>
            </div>
            <p class="card-text genre-color"><small><i class="fas fa-music"></i> <%= user_vinyl.vinyl.genre.name %></small></p>
          </div>
          <div class="h-75 p-3 link-card justify-content-end align-items-center d-flex flex-column">
            <%= link_to icon('fas', 'trash-alt'),  user_vinyl_path(user_vinyl), method: :delete, remote: true, class:"my-trash text-white", id:'trash' %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_vinyls/show.html.erb
<div id="vinyl-without">
  <div class="banner-vinyl d-flex align-items-end justify-content-center" style="background-image: linear-gradient(0deg, rgba(0,0,0,0.8239670868347339) 2%, rgba(253,187,45,0) 50%), url('<%= @user_vinyl.vinyl.cover_url %>'); height: 380px;">
    <div class="tag-wrap d-flex">
      <% @vinyl_tags.each do |vinyl_tag| %>
        <div class="bg-white ml-2 mb-2 py-2 px-3 rounded-pill text-dark font-weight-bold">
          <%= vinyl_tag.tag.title %>
        </div>
      <% end %>
    </div>
    <i id="buttonOk" class="fas fa-tag d-flex bd-highlight ml-auto p-3"></i>
  </div>
  <div id="tag-with" hidden>
    <div class="class-tag-with" style="background-color: #2D4243;">
      <div class="card-tag">
        <div class="top-tag">
          <h2 class="text-center my-3">Choose your tag</h2>
          <%= simple_form_for @user_vinyl do |f| %>
          <div class="d-flex justify-content-center align-items-center">
            <%= f.input :vinyl_tags, collection: @tags, class:"form-control", label: false %>
            <%= f.submit "add tag", class: "btn btn-primary font-weight-bold mb-3" %>
          </div>
          <% end %>

          <div class="tag-suggest">
            <div class="bg-white ml-2 mb-2 py-2 px-3 rounded-pill"><%= link_to @tags.find(4).title, update_tag_user_vinyl_path(@user_vinyl, @tags.find(4)), method: :patch, class: "text-dark text-decoration-none font-weight-bold" %></div>
            <div class="bg-white ml-2 mb-2 py-2 px-3 rounded-pill"><%= link_to @tags.find(33).title, update_tag_user_vinyl_path(@user_vinyl, @tags.find(33)), method: :patch, class: "text-dark text-decoration-none font-weight-bold" %></div>
            <div class="bg-white ml-2 mb-2 py-2 px-3 rounded-pill"><%= link_to @tags.find(22).title, update_tag_user_vinyl_path(@user_vinyl, @tags.find(22)), method: :patch, class: "text-dark text-decoration-none font-weight-bold" %></div>
            <div class="bg-white ml-2 mb-2 py-2 px-3 rounded-pill"><%= link_to @tags.find(14).title, update_tag_user_vinyl_path(@user_vinyl, @tags.find(14)), method: :patch, class: "text-dark text-decoration-none font-weight-bold" %></div>
            <div class="bg-white ml-2 mb-2 py-2 px-3 rounded-pill"><%= link_to @tags.find(7).title, update_tag_user_vinyl_path(@user_vinyl, @tags.find(7)), method: :patch, class: "text-dark text-decoration-none font-weight-bold" %></div>
            <div class="bg-white ml-2 mb-2 py-2 px-3 rounded-pill"><%= link_to @tags.find(34).title, update_tag_user_vinyl_path(@user_vinyl, @tags.find(34)), method: :patch, class: "text-dark text-decoration-none font-weight-bold" %></div>
          </div>
        </div>

        <div class="line">
        </div>

        <div class="bottom-tag my-3">
          <div class="my-tag text-center my-3">
            <h2>My tags</h2>
          </div>
          <div class="d-flex flex-wrap mt-3">
            <% @vinyl_tags.each do |vinyl_tag| %>
              <div class="bg-white ml-2 mb-2 py-2 px-3 rounded-pill">
                <%= link_to vinyl_tag_path(vinyl_tag), method: :delete, class: "text-dark text-decoration-none font-weight-bold" do %>
                  <%= "X #{vinyl_tag.tag.title}" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <i id="buttonTagClose" class="fas fa-times-circle position-absolute"></i>
      </div>
    </div>
  </div>
</div>
  <div class="infos bg-light mb-4" style="height: 42vh">
    <div class="d-flex justify-content-between align-items-center">
      <h2 class="text-primary title-sizing"><%= @user_vinyl.vinyl.title %></h2>
      <small id="rate" class="d-flex align-items-baseline"><%= image_tag 'rating.svg', class:"mr-1" %><strong><%= @user_vinyl.vinyl.stars %></strong></small>
    </div>
    <div class="artist-year">
      <small class="text-muted">by <%= @user_vinyl.vinyl.artist.name %> - <%= @user_vinyl.vinyl.release_date %></small>
    </div>
    <div class="tracks-index mt-3" style="height: 25vh; overflow: scroll">
        <ul class="pl-0 bg-light">
          <% @user_vinyl.vinyl.tracks.each do |track| %>
            <li><%= track.position %>. <%= track.title %></li>
          <% end %>
        </ul>
    </div>
  </div>
</div>
<%# <div class="d-flex w-100 fixed-bottom p-3">
  <% img = image_tag 'back-arrow.svg' %>
  <%# <%= link_to img, user_vinyls_path %>
<%# </div> %>
<%= javascript_pack_tag 'hide_with_js' %>