config/routes.rb
Rails.application.routes.draw do
  get 'suggestions/index'
  get 'suggestions/show'

  devise_for :users
  authenticated :user do
    root to: 'pages#home_user', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'pages#home', as: :unauthenticated_root

  end

  # The vinyls that the user own in his collection:
  resources :user_vinyls, only: [:index, :show, :update, :destroy] do
    member do
      patch :update_tag
    end
  end
  # TODO: :
  # -- SHOULD HAVE --
  # :users
  # :listen
  # :index from other users

  # The vinyls that the user has put in his wish list:
  resources :favorites, only: [:index, :show, :destroy] do
    member do
      post :create_from_favorite
    end
    resources :user_vinyls, only: [:create_from_favorite]
  end

  # The vinyls that the user doesn't own:
  resources :vinyls, only: [:index, :show] do
    collection do
      get :barcode
      get :scan
      get :search
    end
    resources :favorites, only: [:create]
    resources :user_vinyls, only: [:create]
  end

  # The vinyls that are suggested for the user :
  resources :suggestions, only: [:index, :show]
  resources :vinyl_tags, only: [:destroy]
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  def self.find_from_discogs(query_search)
    results_vinyls = Vinyls::DiscogsSearchService.new(query_search).call
    vinyls = []
    results_vinyls.each do |vinyl|
      p vinyl[:tracks]
      genre = Genre.find_or_create_by(name: vinyl[:genre])
      artist = Artist.find_or_create_by(name: vinyl[:artist_name])
      new_vinyl = Vinyl.find_or_create_by(title: vinyl[:title], release_date: vinyl[:released], genre: genre, artist: artist, stars: vinyl[:rating], cover_url: vinyl[:cover_url], discogs_id: vinyl[:discogs_id])
      vinyl[:tracks].each do |track|
        new_track = Track.find_or_create_by(title: track[:title], position: track[:position], vinyl_id: new_vinyl.id)
        new_track.update(milliseconds: track[:milliseconds]) if track[:milliseconds]
      end
      vinyls << new_vinyl
    end
    vinyls
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  def index
    if current_user.user_vinyls.empty?
      @vinyls = Vinyl.all.shuffle.take(10)
    else
      @query = current_user.user_vinyls.sample.vinyl.artist.name
      @vinyls = Suggestion.find_from_discogs(@query)
      @suggestions = @vinyls.select { |vinyl| vinyl == UserVinyl.find_by(user: current_user, vinyl: vinyl) }
    end

    if params[:query].present?
      sql_query = "title ILIKE :query"
      @suggestions = Suggestion.where(sql_query, query: "%#{params[:query]}%")
    else
      @suggestions = Suggestion.all
    end
  end

  def show
    @vinyl = Vinyl.find(params[:id])
    @suggestion = Suggestion.find_by(user: current_user, vinyl: @vinyl)
    @already_in_collec = UserVinyl.find_by(user: current_user, vinyl: @vinyl)
  end
end

app/views/suggestions/index.html.erb
<div class="m-5">
</div>

<div class="d-flex justify-content-between align-items-center m-3">
  <div class="avatar-navbar">
    <%= render 'shared/avatar_navbar' %>
  </div>
  <h2 class="font-weight-bold">Discover</h2>
</div>

<ul class="nav justify-content-between p-3">
  <li class="nav-item font-weight-bold text-hidden"><%= link_to 'Collection', user_vinyls_path, style:"color:#c2c2c2;" %></li>
  <li class="nav-item font-weight-bold ">Suggestions</li>
  <li class="nav-item font-weight-bold text-hidden"><%= link_to 'Wishlist', favorites_path, style:"color:#c2c2c2;" %></li>
</ul>


<div class="card-vinyl">
  <div class="mx-3 mb-3 content-search">

  <% if @vinyls %>
    <% @vinyls.each_with_index do |vinyl, index| %>
      <div class="card-search  py-4 d-flex">
        <%= link_to vinyl_path(vinyl) do %>
          <div class="container-img ">
            <img class="photo-sizing position-relative" src="<%= vinyl.cover_url %>">
          </div>

          <div class="container-infos w-50 px-3 py-2 d-flex flex-column justify-content-between">
            <div>
              <h6 class="card-text title-sizing text-white"><%= vinyl.title %></h6>
              <p class="card-text text-sizing text-white"><%= vinyl.artist.name %></p>
            </div>
            <p class="card-text genre-color"><small><i class="fas fa-music"></i> <%= vinyl.genre.name %></small></p>
          </div>
          <div class="h-75 p-3 link-card justify-content-between align-items-center d-flex flex-column">
            <div>
              <%= link_to icon('fas', 'plus'), vinyl_user_vinyls_path(vinyl), method: :post %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

<div class="d-flex w-100 fixed-bottom p-3">
  <% img = image_tag 'back-arrow.svg' %>
  <%= link_to img, authenticated_root_path %>
</div>

app/views/suggestions/show.html.erb
<h1>Suggestions#show</h1>
<p>Find me in app/views/suggestions/show.html.erb</p>